import { describe, expect, it } from "vitest";
import { formatAssessmentSummary } from "./formatAssessmentSummary";

describe("formatAssessmentSummary", () => {
  it("formats a complete assessment summary", () => {
    const result = formatAssessmentSummary({
      id: "1",
      patientName: "Jane Doe",
      riskCategory: "Moderate",
      riskScore: 78,
      age: 52,
      gender: "Female",
      bmi: 29.8,
      hba1cLevel: 6.2,
      bloodGlucoseLevel: 130,
      hypertension: false,
      heartDisease: false,
      smokingHistory: "No",
      createdAt: "2026-06-06T12:00:00.000Z",
      factors: [],
      prediction: null,
    } as any);

    expect(result).toContain("Risk Assessment Summary");
    expect(result).toContain("Risk Category: Moderate");
    expect(result).toContain("Risk Score: 78.0%");
    expect(result).toContain("Age: 52");
    expect(result).toContain("Gender: Female");
    expect(result).toContain("BMI: 29.8");
    expect(result).toContain("HbA1c: 6.2%");
    expect(result).toContain("Blood Glucose: 130 mg/dL");
    expect(result).toContain("Generated by Clinical Insight Engine");
  });
});
