import type { AssessmentResponse } from "@shared/routes";

const formatNumberValue = (value: unknown, suffix = ""): string => {
  if (value === undefined || value === null || value === "") {
    return "N/A";
  }
  const numberValue = Number(value);
  if (!Number.isFinite(numberValue)) {
    return String(value);
  }
  return `${numberValue}${suffix}`;
};

/**
 * Format Assessment Summary.
 * @param assessment - The assessment parameter.
 * @returns The result of the operation.
 */
export function formatAssessmentSummary(assessment: AssessmentResponse): string {
  const category = assessment.riskCategory || "Unknown";
  const score = assessment.riskScore !== undefined && assessment.riskScore !== null
    ? `${Number(assessment.riskScore).toFixed(1)}%`
    : "N/A";
  const age = assessment.age !== undefined && assessment.age !== null
    ? String(assessment.age)
    : "N/A";
  const gender = assessment.gender || "Unknown";
  const bmi = assessment.bmi !== undefined && assessment.bmi !== null
    ? Number(assessment.bmi).toFixed(1)
    : "N/A";
  const hba1c = assessment.hba1cLevel !== undefined && assessment.hba1cLevel !== null
    ? `${Number(assessment.hba1cLevel).toFixed(1)}%`
    : "N/A";
  const bloodGlucose = assessment.bloodGlucoseLevel !== undefined && assessment.bloodGlucoseLevel !== null
    ? `${Number(assessment.bloodGlucoseLevel).toFixed(0)} mg/dL`
    : "N/A";

  return [
    "Risk Assessment Summary",
    "",
    `Risk Category: ${category}`,
    `Risk Score: ${score}`,
    "",
    `Age: ${age}`,
    `Gender: ${gender}`,
    "",
    `BMI: ${bmi}`,
    `HbA1c: ${hba1c}`,
    `Blood Glucose: ${bloodGlucose}`,
    "",
    "Generated by Clinical Insight Engine",
  ].join("\n");
}
